POST http://127.0.0.1:10001/users/
Accept: application/json
Content-Type: application/json

{
  "username": "ivan",
  "password": "P@ssw0rd",
  "role": "user"
}

###

POST http://127.0.0.1:10001/auth/
Accept: application/json
Content-Type: application/json

{
  "username": "ivan",
  "password": "P@ssw0rd"
}
###

PUT http://127.0.0.1:10001/auth/
Accept: application/json
Content-Type: application/json

{
  "refresh_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2NDc3MjkwNDV9.-eeK5s4qxvdzEsIutBHG8FuO3zpFveBgyoyLPGvK4NU"
}

###

GET http://127.0.0.1:10001/movies/
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2MzY0OTg5NDh9.l9tAQfgXhm9LrjS-uB8WpvB0AV2i94GLh4mO86f3zj8

###

GET http://127.0.0.1:10001/movies/1
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2MzY0OTg5NDh9.l9tAQfgXhm9LrjS-uB8WpvB0AV2i94GLh4mO86f3zj8

###

GET http://127.0.0.1:10001/movies/?genre_id=4
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2MzY0OTg5NDh9.l9tAQfgXhm9LrjS-uB8WpvB0AV2i94GLh4mO86f3zj8

###

GET http://127.0.0.1:10001/movies/?year=1980
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2MzY0OTg5NDh9.l9tAQfgXhm9LrjS-uB8WpvB0AV2i94GLh4mO86f3zj8

###

GET http://127.0.0.1:10001/directors/
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2MzY0OTg5NDh9.l9tAQfgXhm9LrjS-uB8WpvB0AV2i94GLh4mO86f3zj8

###

GET http://127.0.0.1:10001/directors/2
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2MzY0OTg5NDh9.l9tAQfgXhm9LrjS-uB8WpvB0AV2i94GLh4mO86f3zj8

###

GET http://127.0.0.1:10001/genres/
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InZhc3lhIiwicGFzc3dvcmQiOiJteV9saXR0bGVfcG9ueSIsImV4cCI6MTYzNjQ5NTI2N30.xtj2sdgIH5L_2t2oEdjtfSBGv4zbuoJmhEcYB11P46g

###

GET http://127.0.0.1:10001/genres/1
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJwYXNzd29yZCI6IjE2MWViZDdkNDUwODliMzQ0NmVlNGUwZDg2ZGJjZjkyIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjM2NDk1ODQyfQ.N4NwXoObSe49nGmYC3bBgf9wRtS-_BRSS0fC1Kltoqs

###

GET http://127.0.0.1:10001/movies/21
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJwYXNzd29yZCI6IjE2MWViZDdkNDUwODliMzQ0NmVlNGUwZDg2ZGJjZjkyIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjM2NDk1ODQyfQ.N4NwXoObSe49nGmYC3bBgf9wRtS-_BRSS0fC1Kltoqs

###

POST http://127.0.0.1:10001/movies/
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2MzY0OTg5NDh9.l9tAQfgXhm9LrjS-uB8WpvB0AV2i94GLh4mO86f3zj8

{
  "title": "Гарри Поттер мой кумир!",
  "trailer": "таким фильмам не нужны трейлеры",
  "year": 1990,
  "rating": 10,
  "description": "10 из 10!"
}

###

PUT http://127.0.0.1:10001/movies/21
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2MzY0OTg5NDh9.l9tAQfgXhm9LrjS-uB8WpvB0AV2i94GLh4mO86f3zj8

{
  "id": 21,
  "title": "-------",
  "trailer": "-----",
  "year": 0,
  "rating": 0,
  "description": "0 из 10!",
  "genre_id": 1,
  "director_id": 1
}

###

DELETE http://127.0.0.1:10001/movies/21
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJwYXNzd29yZCI6IjE2MWViZDdkNDUwODliMzQ0NmVlNGUwZDg2ZGJjZjkyIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjM2NDk1ODQyfQ.N4NwXoObSe49nGmYC3bBgf9wRtS-_BRSS0fC1Kltoqs